### ISSUE TITLE
Cache queries are logged even with option to not log them

### ISSUE THREAD

**Issue by tommyalvarez** [ruckus/active-record-query-trace#30]
Hi,
I'm using active_record_query_trace (1.5.4)  with Rails 5.1.5. 

This is my initializer config:

```
if Rails.env.development?
  ActiveRecordQueryTrace.enabled = true
  ActiveRecordQueryTrace.colorize = 'light purple'
  ActiveRecordQueryTrace.ignore_cached_queries = true
end
```
However, ignored cached queries is not working:

![image](https://user-images.githubusercontent.com/2272455/40282640-d1a2ee18-5c48-11e8-8ce1-b48985b2af39.png)

Any idea why?

**Comment by tommyalvarez** [comment]
@ruckus Are you still mantaining this project??

**Comment by ruckus** [comment]
@tommyalvarez no, i'm not actively maintaining it. If you are interested in taking it over I can assign it to you....

**Comment by brunofacca** [comment]
@ruckus, I think this project is very useful (I wish I've found it sooner) and I'm interested in maintaining it.

**Comment by sgbett** [comment]
Hi,

It looks like this fix breaks Rails 4 compatibility as the payload is structured like this: 
```ruby
{ 
    :sql=>..., 
    :binds=>..., 
    :name=>"CACHE", 
    :connection_id=>...
}
```
Doubt there is much appetite for a Rails 4 fix, but for anyone else that may be struggling with this I've pushed a quick hack here https://github.com/sgbett/active-record-query-trace/commit/2ad89743907b3132f894fef485fa0dce35f8df7d

**Comment by brunofacca** [comment]
Hi @sgbett. Thanks for the fix. Unfortunately, Rails 4.0 is no longer supported. Rails 4.2 is still supported and the last merged PR had a green build when tested with Rails 4.2.11.1.

**Comment by sgbett** [comment]
Hi! Looks like the spec is passing because the match is:

`expect(log).not_to match(/CACHE User Load.*#{described_class::BACKTRACE_PREFIX}/m)`

The log actually contains the line:

`D, [2019-10-08T22:15:40.703006 #58504] DEBUG -- :   CACHE (0.0ms)  SELECT "users".* FROM "users"`

This commit https://github.com/sgbett/active-record-query-trace/commit/b0b70a10006dc5e21e94f3b9bc4f459f57ecd2a8 will make the test go red (with the commit above making it go green again) when testing with RAILS_VERSION="~>4.2.0"

I tried testing against 5 (ie not setting RAILS_ENV) but I ran into a sqlite3 conflict (for some reason it wanted 1.4.x but I had 1.3.x installed) I tried adding ~>1.4 to my local build but that caused this: 

```
An error occurred while loading ./spec/active_record_query_trace_spec.rb.
Failure/Error: ActiveRecord::MigrationContext.new(MIGRATIONS_PATH).up

ArgumentError:
  wrong number of arguments (given 1, expected 2)
# /Users/simon/.rvm/gems/ruby-2.6.4/gems/activerecord-6.0.0/lib/active_record/migration.rb:1028:in `initialize'
# ./spec/db/setup.rb:18:in `new'
# ./spec/db/setup.rb:18:in `<top (required)>'
# ./spec/spec_helper.rb:10:in `require'
# ./spec/spec_helper.rb:10:in `<top (required)>'
# ./spec/active_record_query_trace_spec.rb:3:in `require'
# ./spec/active_record_query_trace_spec.rb:3:in `<top (required)>'
/private/opt/ruby/active-record-query-trace/spec/db/setup.rb:3: warning: already initialized constant MIGRATIONS_PATH
/private/opt/ruby/active-record-query-trace/spec/db/setup.rb:3: warning: previous definition of MIGRATIONS_PATH was here
``` 

Which I didn't really care to investigate any further ;) im happy with my hack for now until I get things moved over to rails 5!

**Comment by brunofacca** [comment]
Ah, I see. In that case, if you want to submit a PR, I'd gladly merge it as soon as all CI checks are passing.
